### ISSUE TITLE
Couldn't find a way to contact you.

### ISSUE THREAD

**Issue by ArshpreetS** [xnomas/PicoCTF-2021-Writeups#1]
Hello xnomas, I am Arshpreet and I was looking at one of your writeups on picoCTF https://github.com/xnomas/PicoCTF-2021-Writeups/blob/main/Transformation/README.md. 

I am new to the field of cyber security and have recently started playing CTFs and I wanted to ask you, how did you find out that the given string was encoded in UTF-16 and also if possible explain a little bit about it too because I couldn't understand it over the internet.

Thanks for the writeup :)

**Comment by xnomas** [comment]
Hi Arshpreet,

Looking at the code given you can see this 
```py
enc ''.join([chr((ord(flag[i]) << 8) + ord(flag[i + 1])) for i in range(0, len(flag), 2)])
```
I don't know how familiar you are with python, but this takes two ascii values of the characters from our flag. Here:
```py
chr((ord(flag[i]) << 8) + ord(flag[i + 1])
```
Shifts the first by 8 bits to the left and adds the ascii value of the following letter. Then converted back to a character, this gives us: `灩捯䍔䙻ㄶ形楴獟楮獴㌴摟潦弸彥ㄴㅡて㝽`

You could easily try to solve with code like this:
```py
for i in range(0,len(enc)):
...     print(chr(ord(enc[i]) >> 8),end='')
...
pcCF1_isis3do__1107
```
But as you can see, the bit shift on its own is not enough. From here you could have guessed it to be a difference in encoding. I decided to use the tool cyberchef (as mentioned in the writeup), cause it solves it for you. Essentially we are missing a few pieces of the flag. You could also try bruteforcing it, and find the pieces one by one. 

```py
for i in range(0,len(enc)):
...     print(ord(enc[i]) >> 8)
...
112
99
67
70
49
95
105
115
105
115
51
100
111
95
95
49
49
48
55
```
If I elaborate, here are all the ascii values after the bit shift. We know the output will be only printable characters, so you could try to either find the right encoding, or try and find what two numbers in the printable character range give you the values above. 

I prefer the `cyberchef` route just for convenience. Let me know if there is something else, you'd like explained. 

*Note: My explanation is certainly not the only way or the best way to do it. I recommend doing more research online :)*

**Comment by ArshpreetS** [comment]
Thank you so much for the efforts.
One more thing, is there any way I can "join" you. I mean I saw it in many talks that you should have a community to get into cyber security and I have none for now and I don't know where to start.
Anything?

**Comment by xnomas** [comment]
You can join the PicoCTF discord server here: https://discord.com/invite/WQGdYaB

There should be a section for people that are looking for a team :) You can find some people there. 

Have a good one and keep learning! 🥇
